### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by dcousens** [dcousens/ordinal#1]
@ghost it seems you stopped publishing this package on GitHub and therefore the npm link is dead.

Would you be happy to add me as a contributor to https://www.npmjs.com/package/ordinal and I can release this package as version `1.0.0`?

Understandable if not,  I'll publish under another name.

The code is entirely new, so I didn't carry over the license,  but I can reference you if you'd like...

**Comment by dcousens** [comment]
ping @0x0uLL?

**Comment by ghost** [comment]
@dcousens You're all set. Enjoy 🎉

**Comment by dcousens** [comment]
Thanks!
