### ISSUE TITLE
Instead of using `indicator`, pass a `boolean` as the second param.

### ISSUE THREAD

**Issue by joshuapinter** [dcousens/ordinal#3]
Maybe something like this: 

```js
// Method definition: ordinal( number, includeNumber = true ).

ordinal(2);        // "2nd"
ordinal(2, false); // "nd"
ordinal(2, true);  // "2nd"
```

Defaults to include the number but you can pass `false` to the second param and it will not include the number. 

Thoughts?

**Comment by dcousens** [comment]
@joshuapinter I suppose,  what is the usecase/advantage though?

**Comment by joshuapinter** [comment]
Just more intuitive, instead of having to import something else called "indicator" which is not very self-explanatory.

In my case, which probably isn't too uncommon, sometimes you need to include the number and sometimes you don't. 

Happy to do a PR if you are open to the idea.

**Comment by dcousens** [comment]
~`indicator` is truly a terrible name~, it is more a "suffix-only" option - alas this API was mimicking the previous versions of this module (which I inherited from someone else).

I'm not against the idea that the existing is bad,  but,  I don't think the proposed syntax above is anymore intuitive.

Defaulted positional arguments can be messy too if users aren't careful,  think `parseInt` and `Array.prototype.map`.

**Comment by joshuapinter** [comment]
Ha. We agree on that.

I'm not a fan of unnamed params passed in either, actually. 

What about an options Object as the second params with `suffixOnly`, like this: 

```js
ordinal( 2 );                      // "2nd"
ordinal( 2, {suffixOnly: true} );  // "nd"
ordinal( 2, {suffixOnly: false} ); // "2nd"

**Comment by dcousens** [comment]
@joshuapinter I like it.
It also easily allows for language extensions if anyone ever needs it.

PR accepted,  as `2.0.0`

**Comment by joshuapinter** [comment]
👍 I'll take a look when I get time.

**Comment by anomalousitem** [comment]
> `indicator` is truly a terrible name, it is more a "suffix-only" option - alas this API was mimicking the previous versions of this module (which I inherited from someone else).

FWIW, the name was based on the info at https://en.wikipedia.org/wiki/Ordinal_indicator#English. The very beginning of the article states:

> In written languages, an ordinal indicator is a [character](https://en.wikipedia.org/wiki/Character_(typography)), or group of characters, following a [numeral](https://en.wikipedia.org/wiki/Numerical_digit) denoting that it is an [ordinal number](https://en.wikipedia.org/wiki/Ordinal_number_(linguistics)), rather than a [cardinal number](https://en.wikipedia.org/wiki/Names_of_numbers_in_English#Cardinal_numbers).

Sorry for the random drive by. On a closed PR nonetheless. I'm the original author that you inherited this from. I was weirdly reminded of this library today so just paying a little visit. Figured I might as well explain my terrible decision from eight years ago while I'm here 😅.

**Comment by dcousens** [comment]
Thanks for the followup @anomalousitem, honestly that's great that `indicator` is part of the ordinal nomenclature. I should have looked into that before I claimed it was "terrible"; that's on me, sorry 💙.

I don't know if it's the best path forward compared to `suffix` (as even the Wikipedia article refers), but, it's not _wrong_ by any stretch.
