### ISSUE TITLE
Would be nice if passing string worked

### ISSUE THREAD

**Issue by grimmdude** [dcousens/ordinal#4]
It would be easier to use if a number in string format would be allowed without needing to first convert it.

**Comment by dcousens** [comment]
@grimmdude can you provide an example of what you mean?

**Comment by grimmdude** [comment]
Hi @dcousens,

Thanks for your response.  Sure, I feel like this should just work:

```js
// Fails since this is a string
ordinal('4');
```
This is obviously a very simple example, but there are some cases where a variable number could be represented as a string (some JSON APIs).

I could first use `parseInt()` on the number, but it seems intuitive to not have to.  Perhaps the module could attempt to convert into a number here before failing?

https://github.com/dcousens/ordinal/blob/master/index.js#L4

**Comment by dcousens** [comment]
@grimmdude I don't mind either way,  personally that isn't intuitive for me,  but,  I tend to prefer more statically typed development.

**Comment by dcousens** [comment]
Maybe do an `isFinite` call in place of the check in https://github.com/dcousens/ordinal/blob/master/index.js#L4

I'd be happy with that :+1:

**Comment by dcousens** [comment]
Though,  additionally it would need to be `parseInt`,   `21.3st` doesn't make sense.

**Comment by grimmdude** [comment]
Hi @dcousens,

It's up to you, I understand the preference for statically typed development.  This was my first impression when using the module with an API supplied JSON (string) property which contained a numeric value.  Sort of a hassle, but not a big deal to first run `parseInt()` on the value.  

-Garrett
